name: "Scan Dockerfile"
description: "AI-powered Dockerfile scanner for security, optimization, and best practices with automated issue reporting."
author: "Joao Pedro Ramos de Oliveira"

inputs:
  GITHUB_TOKEN:
    description: |
      GitHub token for authentication. Must have permissions:
      - contents:read, issues:write, pull-requests:write
    required: true

  API_TOKEN:
    description: "Gemini API key for AI-powered suggestions"
    required: true

outputs:
  COMMENT_ID:
    description: "ID of the comment where the scan results were posted"
  ISSUE_ID:
    description: "ID of the issue created with scan results"
  SCAN_STATUS:
    description: "Overall scan status (success/warning/error)"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "shield"
  color: "blue"
