name: "Build index.js for GitHub Action"
#TODO: Add a webhook to my action to trigger action action-main(exceute scan-dockerfile)
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - feature/new-architecture
    paths-ignore:
      - "**.md"
      - "dist/**" #avoid infinite loop
      - ".github/workflows/**"
      - ".gitignore"
      - ".vscode/**"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the action
        run: npm run build

      - name: Commit and push built action
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 Update built action"
            git push
          fi

      - name: Upload built action
        uses: actions/upload-artifact@v4
        with:
          name: action
          path: dist
  test-execution:
    #TODO Make a matrix to run tests in parallel and use only steps. using variable
    runs-on: ubuntu-latest
    needs: build
    env:
      # ✅ Variáveis parametrizáveis do job
      TEST_TOKEN: ${{ secrets.TOKEN_API_GIT }}
      TEST_REPO_1: "joao-pedro-rdo/teste-scan"
      TEST_REPO_2: "joao-pedro-rdo/action-main"
      GITHUB_API_VERSION: "2022-11-28"
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      COMMIT_SHA: ${{ github.sha }}
      BRANCH: ${{ github.ref_name }}

    steps:
      - name: ✅ Test Action - Simple Dispatch
        env:
          TARGET_REPO: ${{ env.TEST_REPO_1 }}
          EVENT_TYPE: "teste-da-api-on-demand-test"
        run: |
          echo "🚀 Triggering test on repository: $TARGET_REPO"
          echo "📝 Event type: $EVENT_TYPE"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TEST_TOKEN" \
            -H "X-GitHub-Api-Version: $GITHUB_API_VERSION" \
            https://api.github.com/repos/$TARGET_REPO/dispatches \
            -d "{\"event_type\":\"$EVENT_TYPE\"}"

          echo "✅ Test dispatch sent successfully"

      - name: ✅ Test Action - Advanced Dispatch with Payload
        env:
          TARGET_REPO: ${{ env.TEST_REPO_2 }}
        run: |
          echo "🚀 Triggering advanced test on repository: $TARGET_REPO"
          echo "📝 Commit: $COMMIT_MESSAGE"
          echo "📝 SHA: $COMMIT_SHA"
          echo "📝 Branch: $BRANCH"

          EVENT_TYPE="teste-da-api-on-demand-$(date +'%Y%m%d-%H%M%S')"
          echo "📝 Event type: $EVENT_TYPE"

          PAYLOAD=$(jq -n \
            --arg event_type "$EVENT_TYPE" \
            --arg commit "$COMMIT_MESSAGE" \
            --arg sha "$COMMIT_SHA" \
            --arg branch "$BRANCH" \
            '{event_type: $event_type, client_payload: {commit: $commit, sha: $sha, branch: $branch}}'
          )

          echo "📋 Payload: $PAYLOAD"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TEST_TOKEN" \
            -H "X-GitHub-Api-Version: $GITHUB_API_VERSION" \
            https://api.github.com/repos/$TARGET_REPO/dispatches \
            -d "$PAYLOAD"

          echo "✅ Advanced test dispatch sent successfully"
